### ISSUE TITLE
[BUG]自定义页面的URL，总是会带上userkey

### ISSUE THREAD

**Issue by challengesoflife** [Kooboo/Kooboo#131]
![image](https://user-images.githubusercontent.com/33093653/84457013-21c64280-ac94-11ea-9181-dcb936b1c88a.png)
如图，我将页面的URL设置成我期望的格式，保存后，生成的页面的确如设置的格式，但是不知道受什么影响过一段时间就会自动加上userkey，这时再把这个URL设置一下，就又对，但过段时间又加上了userkey，预估应该是程序内部哪里存在点问题。

**Comment by koobooteam** [comment]
这个问题已经修复并且提交！

原先这个URL的都路由都是动态， 现在如果出现 {}， 之类的自定义路由， 不再动态指定！

**Comment by challengesoflife** [comment]
> 这个问题已经修复并且提交！
> 
> 原先这个URL的都路由都是动态， 现在如果出现 {}， 之类的自定义路由， 不再动态指定！

谢谢回复！
