### ISSUE TITLE
Can kooboo run on iis server?

### ISSUE THREAD

**Issue by hyzx86** [Kooboo/Kooboo#15]
Can kooboo run on iis server?

**Comment by koobooteam** [comment]
In this case, you run IIS on port 80 as proxy server, and Kooboo in the back with different port.

**Comment by hyzx86** [comment]
But , how can I  change the kooboo server's  default port "80" to another  port number?

**Comment by hyzx86** [comment]
目前的端口默认是80 ，如果80端口被占用则会改变到81
那么如果服务器重启了，kooboo server 比IIS先启动 ，
那么 KOOBOO会不会占用80 端口 导致IIS 80端口的站点无法启动？

**Comment by hyzx86** [comment]
找到了 AppSettingsUtility.Get("Port"); ，可以在appsettings 里面加

**Comment by koobooteam** [comment]
改一下配置文件就可以的。
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <appSettings> 
    <add key="CmsLang" value="en"/> 
    <add key="AllowUsers" value="*"/>
    <add key="DefaultUser" value="admin, admin"/>
    **<add key="Port" value="81"/>**
  </appSettings> 
</configuration>

**Comment by hyzx86** [comment]
我直接改成88 再启动，还显示的81 噢

**Comment by hyzx86** [comment]
OK , Thanks ！

**Comment by koobooteam** [comment]
![port89](https://user-images.githubusercontent.com/4032195/54351614-d127fa00-468a-11e9-9718-cd983493fd5d.png)

This is strange, I just tried it, works very fine like above.  Maybe I have two extra ** in above code, you need to remove them. 

`<add key="Port" value="89"/>`
