### ISSUE TITLE
Is it possible that Kooboo can run without Kooboo.App?

### ISSUE THREAD

**Issue by Smilefounder** [Kooboo/Kooboo#156]
Hi Kooboo team,

Is it possible to run Kooboo entire projects without Kooboo.App? Like the old Kooboo version. Then I just needs to publish the source to iis folder then run only.

I asked this question because it seam possible. But I'm not quite sure how.

Thanks for the great work so far!

Best regards,
Huy Nguyen

**Comment by koobooteam** [comment]
Hi Huy, 

The new Kooboo use Kestrel WebServer, which is a self-hosted application. To run it behind IIS, you need to configure "Reverse Proxy". 

See: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-5.0

**Comment by Smilefounder** [comment]
Hi @koobooteam / Guoqi Zheng

Thanks for the confirmation. I have configured Reverse Proxy, However there is an issue with Reverse Proxy that if Kooboo.App is run with a different port than 80.

For example, 
- Kestrel running port is 81.
- Site domain A Reverse Proxy to 127.0.0.1:81
- Site domain B Reverse Proxy to 127.0.0.1:81
- Add HomePage with URL / to both domains (A & B)

The result:
- Access both sites will lead you to the login page instead of displaying the HomePage for each site
- Add a binding domain for port 81, then both sides will display only 1 and same HomePage

Kindly help advice.
Thanks for the great work so far!

**Comment by koobooteam** [comment]
Kooboo should be configured like below to listen on port 81. 

![config_port](https://user-images.githubusercontent.com/4032195/99937859-9a800d80-2da1-11eb-8545-fd7194afabb8.png)

if still problem. Zip the AppData folder, and send it to my email(you got my email), then I will look into your configuration.

**Comment by Smilefounder** [comment]
Thanks @koobooteam I found the root cause. It is because IIS not forward the host information so it always the same 

Fixed by run the following command to force IIS to not change the Host header.
`\Windows\System32\inetsrv\appcmd.exe set config -section:system.webServer/proxy -preserveHostHeader:true /commit:apphost`
