### ISSUE TITLE
Sample script is out of date and I can not import

### ISSUE THREAD

**Issue by ilovetosmilearound** [Kooboo/Kooboo#162]
Hi @koobooteam , I tried to import the following sample kScript however the error occurred. Kindly advice.
https://www.kooboo.cc/Example/userproject.zip

**Comment by koobooteam** [comment]
Hi

I download the latest version from www.kooboo.com

Import the sample project, everything works fine. 

Do you have any error message?

**Comment by ilovetosmilearound** [comment]
Thanks, it succeed imported to Kooboo local project. But it is not able to import through Kooboo online version. Thanks.
