### ISSUE TITLE
MySQL > Add more than 3 columns with TEXT type > MySQL error: Row size too large

### ISSUE THREAD

**Issue by Smilefounder** [Kooboo/Kooboo#177]
`Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs`

**Comment by huanent** [comment]
It is recommended that you use Navicat to manage mysql. The built-in SQL manager currently does not support setting the length of the field. The default is VARCHAR (Max).

**Comment by Smilefounder** [comment]
Thanks. Wellnoted.
