### ISSUE TITLE
Is it possible to "import JS file or Module" from kScript?

### ISSUE THREAD

**Issue by Smilefounder** [Kooboo/Kooboo#180]
Hi @koobooteam , @huanent 

As in Kooboo docs mentioned that the JS engine is ES5. I have tried to import an external JS file/module however it doesn't work.

And then I think it is NOT possible for security reasons, is it correct?

Or is there any way to import an external JS library that we can use within kScript? Else, we have to write an extension (C#).

Kindly advicce.

**Comment by huanent** [comment]
You can use 
```
k.import("xxx");
```
to import a code (not script,script for frontEnd,code for backEnd)

**Comment by Smilefounder** [comment]
Thanks @huanent , so is it meant that we just able to import kScript from kScript. But how about kScript import any NodeJS module that we upload to server?

**Comment by huanent** [comment]
Kooboo just build-in a Jint jsEngine, not nodejs runtime,so we can't import a NodeJS module

**Comment by Smilefounder** [comment]
Thanks @huanent  well noted.
