### ISSUE TITLE
I am very much looking forward to this triumphant return, a new look.

### ISSUE THREAD

**Issue by pgy866** [Kooboo/Kooboo#2]
I am very much looking forward to this triumphant return, a new look.
非常期待这次凯旋归来，焕然一新。

Can the source code now run?How should I operate?
现在的源码是否可以跑起来呢？我该如何操作？

**Comment by koobooteam** [comment]
Very much good to run. 

You can either download the binary release from www.kooboo.com, or grab a copy of the source code here and open the kooboo.sln.
