### ISSUE TITLE
居然充斥着goto语句？？！！你们是认真的？

### ISSUE THREAD

**Issue by duststarr** [Kooboo/Kooboo#20]
今天clone一份，半天也没运行起来。
看了下代码，居然大量使用goto语句？？！！！
我的天啊

**Comment by koobooteam** [comment]
是的， 正常情况下是不应该使用goto的， 从程序设计的一些教课书来看都是这样子说的！ 

你看到的应该是DOM的解析。 因为我们为了保证100%忠于W3C的文档，我们是一行行翻译 W3C中关于Document Object Model的定义。所以在这些地方用了许多 的GOTO， 是为了忠于标准文档定义， 其他地方应该是没有的。

**Comment by koobooteam** [comment]
你没有运行起来的原因是？？？ 正常应该是没有问题的。 初始项目是Kooboo.App
