### ISSUE TITLE
Image width and height do not update after reupload

### ISSUE THREAD

**Issue by hrvoje-grabusic** [Kooboo/Kooboo#225]
Image width and height do not update after reupload resulting in wrong aspect ratio during resize.

To reproduce: 
1. Upload and image in one aspect ratio
2. Open the image link and set a width param
3. Change image aspect ration and reupload
4. Open the image link and set a width param and see the image is resized with old aspect ratio

If the image is deleted and and then uploaded this doesn't happen.

Fix:
In the Image.cs model the has function needs to include width and height.
This solves the problem.

**Comment by kun18911** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by koobooteam** [comment]
Thanks. will  include direct

**Comment by koobooteam** [comment]
It has been fixed! thanks for reporting. will push a new commit today
