### ISSUE TITLE
对框架组件Kooboo.Data和Kooboo.Sites变动的疑问

### ISSUE THREAD

**Issue by gleox** [Kooboo/Kooboo#227]
我非常喜欢你们的框架，许多组件都是自研的，我一直在关注你们的进展。自2021年以来，你们的代码更新频率明显降低，我一度以为你们已经停止维护。

从2.1版本开始，你们移除了组件 Kooboo.Data 和 Kooboo.Sites 的源代码，且仓库中的 NuGet 包也进行了混淆。请问这样做有什么特别的考量吗？未来是否有可能重新发布源代码？

**Comment by koobooteam** [comment]
这样子做的原因是为了商业化， 为了让每个人都 可以在上面卖东西， 未来如果开放， 估计也是对部分人开放， 以免受到攻击！ 

现在可以看下
https://www.mobanplus.com 

很快每个人都可以在上面卖自己的东西！
