### ISSUE TITLE
Add new menu to site dashboard 

### ISSUE THREAD

**Issue by carlosmorenoaguilera** [Kooboo/Kooboo#228]
hi, i want develop a custom menu and functionality inside dashboard menu of each site 

how i can accomplish that without rewrite all source by my self?  there is way to add any plugin or addons for develop a new system functionality ? 

thank you any help will be appreciated 

![Screenshot_20241110-130457_Chrome](https://github.com/user-attachments/assets/df4502ce-0090-45ba-abb9-7d8d5ca08584)

**Comment by huanent** [comment]
Please check this post: http://forum.kooboo.com/thread/550395f7-9d0a-4369-86ca-dac2ec5b87ce

**Comment by carlosmorenoaguilera** [comment]
> Please check this post: http://forum.kooboo.com/thread/550395f7-9d0a-4369-86ca-dac2ec5b87ce

thank you!
