### ISSUE TITLE
What type of license does Kooboo use?

### ISSUE THREAD

**Issue by carlosmorenoaguilera** [Kooboo/Kooboo#230]
hi i'm interested to use this software seems awesome, now im concerned about license, im just solo developer trying to make tools, web pages and selling software.
some headers of files say that has copyright and all right reserved but all repo say that is eclipse license and i want to be respectful.

**Comment by koobooteam** [comment]
Yes, it is Eclipse license, feel free to use it private or commercially. 

We do have some source protected, this is designed to enable developers to sell software writted in Kooboo in the future. 

There will not be any limitation for any one to use this software. 

We will remove the license in source code. Thanks for letting us know.

**Comment by carlosmorenoaguilera** [comment]
> Yes, it is Eclipse license, feel free to use it private or commercially.
> 
> We do have some source protected, this is designed to enable developers to sell software writted in Kooboo in the future.
> 
> There will not be any limitation for any one to use this software.
> 
> We will remove the license in source code. Thanks for letting us know.

thank you 🙂
