### ISSUE TITLE
泛型序列化

### ISSUE THREAD

**Issue by nodyang** [Kooboo/Kooboo#28]
,An error occurred on symbol 6 , it's r
![image](https://user-images.githubusercontent.com/3090191/69690478-e785c100-1106-11ea-8878-9abdb251986c.png)
![image](https://user-images.githubusercontent.com/3090191/69690497-ff5d4500-1106-11ea-82c8-db9c6d13223a.png)
json.net 是可以解析的

异常信息
BaseResponseInfo`1 type parsing error ,An error occurred on symbol 6 , it's r

**Comment by 1996v** [comment]
1.json字符串首字母是小写，但实体类是首字母大写，可以通过JsonCharacterReadState=JsonCharacterReadStateEnum.InitialUpper配置一下 就可以了。
2.实体类中的类型为long，但是传过来的json字符串中是string，可以通过格式化器JsonDeserializeOption.GlobalKeyFormat来实现
