### ISSUE TITLE
Setting Http verb when defining API

### ISSUE THREAD

**Issue by nhaberl** [Kooboo/Kooboo#59]
Hi,

would be great if we could add the HTTP verb when creating new API route, so we could easier do any kind of REST API style.

**Comment by koobooteam** [comment]
Yes, agreed! Got it. 

You can set header by  k.response.setHeader("", ""), and access to all the request header. You can do a simple validation now yourself.

**Comment by nhaberl** [comment]
Yes thanks, my thought was about transparency so with defining the verbs (and therefore the routes) its much easier to define a RESTful API
Otherwise it could be real messy handling all code for all routes :)

Nevertheless, great software (some kind of roadmap would be helpful)

All the best
